# Generated by Django 5.0.6 on 2024-10-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_profile_role_alter_event_is_cancelled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_organizer',
            new_name='organizer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
