# Generated by Django 5.0.6 on 2024-10-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_event_event_subtype_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_subtype',
        ),
    ]
