# Generated by Django 5.0.6 on 2024-10-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('events', 'Events'), ('play', 'Play'), ('activities', 'Activities'), ('sport', 'Sport')], default='event', max_length=20),
        ),
    ]
