# Generated by Django 5.0.6 on 2024-11-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='quantity_available',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], max_length=20),
        ),
    ]
