# Generated by Django 5.0.6 on 2024-11-04 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_event_cast_or_team_event_event_schedule_event_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cast_or_team',
        ),
        migrations.AddField(
            model_name='event',
            name='cast_or_team_image',
            field=models.ImageField(blank=True, null=True, upload_to='cast_or_team/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.venue'),
        ),
    ]
