# Generated by Django 5.0.6 on 2024-11-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_remove_event_cast_or_team_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='map_link',
            field=models.URLField(max_length=255),
        ),
    ]
