# Generated by Django 5.0.6 on 2024-11-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_alter_venue_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='map_link',
        ),
    ]
