# Generated by Django 5.0.6 on 2024-11-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_remove_venue_map_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='price',
            new_name='price_premium',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='quantity_sold',
            new_name='quantity_available_premium',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='quantity_available',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='price_standard',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity_available_standard',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity_sold_premium',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity_sold_standard',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
