# Generated by Django 5.0.6 on 2024-11-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_rename_price_ticket_price_premium_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CastOrTeamImage',
        ),
    ]
