# Generated by Django 5.0.6 on 2024-11-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_remove_ticket_quantity_available_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price_premium',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price_standard',
        ),
        migrations.AddField(
            model_name='event',
            name='price_premium',
            field=models.DecimalField(decimal_places=2, default=240, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='quantity_booked',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
