# Generated by Django 5.0.6 on 2024-11-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0027_remove_ticket_price_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='quantity_booked',
        ),
        migrations.AddField(
            model_name='event',
            name='price_standard',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
            preserve_default=False,
        ),
    ]
