# Generated by Django 5.0.6 on 2024-11-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0030_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
    ]
