# Generated by Django 5.0.6 on 2024-11-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0031_remove_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('event', 'Event'), ('play', 'Play'), ('activity', 'Activity'), ('sport', 'Sport')], default='event', max_length=20),
        ),
    ]
