# Generated by Django 5.0.6 on 2024-11-11 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0036_event_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('canceled', 'Canceled')], default='booked', max_length=10)),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='adminpanel.ticket')),
            ],
        ),
    ]
