# Generated by Django 5.0.6 on 2024-11-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0037_ticketinstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketInstance',
        ),
    ]
