# Generated by Django 5.0.6 on 2024-11-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0038_delete_ticketinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='card_expiry_date',
            field=models.CharField(default=0.12121212121212122, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(default='0000000000000000', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='cvv',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
