# Generated by Django 5.0.6 on 2024-11-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0040_alter_bankaccount_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
