# Generated by Django 5.0.6 on 2024-11-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0041_alter_bankaccount_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(default='Default Bank', max_length=100),
        ),
    ]
