# Generated by Django 5.0.6 on 2024-11-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0044_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='organizer',
            new_name='user',
        ),
    ]
