# Generated by Django 5.0.6 on 2024-11-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0046_interest_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
