# Generated by Django 5.0.6 on 2024-11-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0049_event_trailer_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='trailer_video_id',
        ),
        migrations.AddField(
            model_name='event',
            name='trailer_video',
            field=models.FileField(blank=True, null=True, upload_to='event_videos/'),
        ),
    ]
