# Generated by Django 5.0.6 on 2024-11-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0050_remove_event_trailer_video_id_event_trailer_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trailer_video',
            field=models.FileField(blank=True, null=True, upload_to='trailer_video/'),
        ),
    ]
