# Generated by Django 5.0.6 on 2024-11-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0051_alter_event_trailer_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trailer_video',
            field=models.FileField(blank=True, null=True, upload_to='event_videos/'),
        ),
    ]
