# Generated by Django 5.0.6 on 2024-11-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0052_alter_event_trailer_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='trailer_video',
        ),
    ]
