# Generated by Django 5.0.6 on 2024-11-19 07:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0053_remove_event_trailer_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('event', 'user')},
        ),
    ]
